# Generated by Django 5.1.1 on 2024-09-26 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technicianmodel',
            options={'verbose_name': 'Technician', 'verbose_name_plural': 'Technicians'},
        ),
    ]
