# Generated by Django 5.1.1 on 2024-09-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0002_alter_technicianmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='technicians/'),
        ),
    ]
