# Generated by Django 5.1.1 on 2024-09-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0003_technicianmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicianmodel',
            name='image',
            field=models.ImageField(default=1, upload_to='technicians/'),
            preserve_default=False,
        ),
    ]
