# Generated by Django 5.1.1 on 2024-09-26 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackmodel',
            options={'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedbacks'},
        ),
        migrations.RenameField(
            model_name='feedbackmodel',
            old_name='tittle',
            new_name='title',
        ),
    ]
